export const Actions = {
  UPDATE_ACTIVE_REQUESTS: 'UPDATE_ACTIVE_REQUESTS',
  LOGIN_API_SUCCEEDED: 'LOGIN_API_SUCCEEDED',
  LOGIN_API_FAILED: 'LOGIN_API_FAILED',
  LOGOUT: 'LOGOUT'
};

export const Routes = {
  LOADING: 'LOADING',
  LOGIN: 'LOGIN',
  LISTTABS: 'LISTTABS',
  REQUEST: 'REQUEST',
  PROFILE: 'PROFILE'
};

export const LocalStorage = {
  USERNAME: 'username',
  PASSWORD: 'password'
};
